### ISSUE TITLE
Definition configuration files

### ISSUE THREAD

**Issue by kwongiho** [DE-labtory/koa-playground#1]
We need to create the configuration files early in the project.

**Comment by kwongiho** [comment]
it fixed & merged by #2 
but it need to modify a bit please check below list if you want to do this.
 - create .github folder
  - move PR_TEMPLATE to .github folder
 - make .gitignore easy to see ( remove all wild-card expression )

**Comment by queuestack** [comment]
Configuration files are defined in #2 
close
