### ISSUE TITLE
Init go project

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/koa-playground#4]

**Comment by queuestack** [comment]
Are we going to use go-lang standards layout? (https://github.com/golang-standards/project-layout)
#5 depends on #4, so tell me if you choose other go-lang project layout

**Comment by queuestack** [comment]
Reference
[https://github.com/PacktPublishing/Echo-Essentials](https://github.com/PacktPublishing/Echo-Essentials)
[https://www.codementor.io/packt/how-to-set-up-a-project-in-echo-mpo39w5zu](https://www.codementor.io/packt/how-to-set-up-a-project-in-echo-mpo39w5zu)

**Comment by queuestack** [comment]
Close with #11
