### ISSUE TITLE
commit message rule

### ISSUE THREAD

**Issue by queuestack** [DE-labtory/koa-playground#9]
I think message rule helps other contributors to follow the history.
I prefer to follow [udacity git commit message guide](https://udacity.github.io/git-styleguide/).
I also find [pandas](http://pandas.pydata.org/pandas-docs/stable/contributing.html#committing-your-code), [angular](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) is good reference.
Commit message rule is not mandatory, but recommend to follow.

**Comment by zeroFruit** [comment]
no one? if so, I'll on it!
